## Testing Einsum

In [7]:
# imports
import numpy as np

In [8]:
a = np.array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

b = np.array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [9]:
# 1. Matrix multiplication (similar to np.matmul(arr1, arr2))
np.einsum('ij, jk -> ik', a, b)

array([[130, 130, 130, 130],
       [230, 230, 230, 230],
       [330, 330, 330, 330],
       [430, 430, 430, 430]])

In [10]:
# 2. Extract elements along the main-diagonal (similar to np.diag(arr))
np.einsum('ii -> i', a)

array([11, 22, 33, 44])

In [11]:
# 3. Sum of all elements (similar to np.sum(arr))
np.einsum('ij -> ', a)

440

In [12]:
# 4. Sum of each column (similar to np.sum(arr, axis=0))
np.einsum('ij -> j', a)

array([104, 108, 112, 116])

In [13]:
# 5. Sum of each row (similar to np.sum(arr, axis=1))
np.einsum('ij -> i', a)

array([ 50,  90, 130, 170])

In [14]:
# 6. Transpose (similar to np.transpose(arr))
np.einsum('ij -> ji', a)

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43],
       [14, 24, 34, 44]])

In [15]:
# 7. Trace (similar to np.trace(arr))
np.einsum('ii -> ', a)

110

In [16]:
# 8. Hadamard product (i.e. element-wise product of two arrays) (similar to arr1 * arr2)
np.einsum('ij, ij -> ij', a, b)

array([[ 11,  12,  13,  14],
       [ 42,  44,  46,  48],
       [ 93,  96,  99, 102],
       [164, 168, 172, 176]])

In [20]:
# 9. Outer product (similar to np.outer(arr1, arr2))
np.einsum('i, j -> ij', [1, 2, 3], [4, 5, 6])

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [21]:
# 10. dot product (similar to np.dot(arr1, arr2))
np.einsum('i, i -> ', [1, 2, 3], [4, 5, 6])

32

In [24]:
# 11. Element-wise squaring (similar to np.square(arr) or arr ** 2)
np.einsum('ij, ij -> ij', b, b)

array([[ 1,  1,  1,  1],
       [ 4,  4,  4,  4],
       [ 9,  9,  9,  9],
       [16, 16, 16, 16]])

In [25]:
# 12. 
np.einsum('ij, ij -> i', a, b)

array([ 50, 180, 390, 680])